<?php
/**
 * Writes docs/COPY-BRIEF.md — the worklist for the writing pass.
 *
 *   php tools/copy-brief.php            # regenerate the document
 *   php tools/copy-brief.php <page-id>  # print one page's briefs to stdout
 *
 * Every {{ ... }} in a content file becomes one numbered line here, with the
 * key path that leads to it, so a writer (or another model) can be handed a
 * page and know exactly which strings to replace and what each has to contain.
 */
require __DIR__ . '/../app/bootstrap.php';

$only = $argv[1] ?? null;

$pages = [];
$totalSlots = 0;
foreach (registry() as $id => $entry) {
    $r = resolve_page($id);
    if ($r['slots'] === []) {
        continue;
    }
    $pages[$id] = ['page' => $r['page'], 'slots' => $r['slots']];
    $totalSlots += count($r['slots']);
}

if ($only !== null) {
    if (!isset($pages[$only])) {
        echo "No unwritten copy in '{$only}' (or no such page id).\n";
        exit(0);
    }
    echo $pages[$only]['page']['url'] . "  —  " . count($pages[$only]['slots']) . " slots\n\n";
    foreach ($pages[$only]['slots'] as $i => $s) {
        printf("%3d. [%s]\n     %s\n", $i + 1, $s['path'], $s['brief']);
    }
    exit(0);
}

// Group by cluster so the document reads in build order rather than id order.
$byCluster = [];
foreach ($pages as $id => $p) {
    $byCluster[$p['page']['cluster'] ?? 'other'][$id] = $p;
}

$out  = "# Copy brief — every unwritten passage on the site\n\n";
$out .= "Generated by `php tools/copy-brief.php`. Do not edit by hand: it is\n";
$out .= "regenerated from the content files, and it shrinks as they are written.\n\n";
$out .= sprintf("**%d passages across %d pages.**\n\n", $totalSlots, count($pages));
$out .= <<<'INTRO'
## How to write against this

Each entry below is one string in a content file under
`app/content/en/pages/`. Find the `{{ ... }}` whose text matches, and replace
the entire string — braces included — with the finished prose. Change nothing
else: not the block order, not the keys, not the structure. A page becomes
live on its own once its last brief is gone, so there is no status to flip and
no way to publish a half-written page by accident.

Read `docs/WRITING-GUIDE.md` before starting. The rules that matter most:

- No processing times, no prices, no approval rates, no client counts, no
  testimonials — anywhere, in any form, including "typically" and "usually".
- Every factual claim must trace to a primary Paraguayan source, and that
  source belongs in the page's `sources` block with the URL actually used.
- Where a brief says a paragraph is mandatory (the "when you should not hire
  us" ones especially), it is mandatory. Those paragraphs are the product.
- Marking prose HTML is allowed only for `<strong>`, `<em>` and `<a href>`.
  Everything else belongs in a block, not in a string.

INTRO;

foreach ($byCluster as $cluster => $group) {
    $out .= "\n---\n\n## " . ucfirst((string) $cluster) . "\n";
    foreach ($group as $id => $p) {
        $file = 'app/content/en/pages/' . str_replace('.', '-', $id) . '.php';
        $out .= "\n### " . $p['page']['h1'] . "\n\n";
        $out .= '`' . $p['page']['url'] . "`  ·  `" . $file . "`  ·  **"
              . count($p['slots']) . " passages**\n\n";
        $out .= '> ' . $p['page']['intent'] . "\n\n";
        foreach ($p['slots'] as $i => $s) {
            $out .= sprintf("%d. `%s`  \n   %s\n", $i + 1, $s['path'], $s['brief']);
        }
    }
}

$out .= "\n---\n\n## Pages with nothing left to write\n\n";
foreach (registry() as $id => $entry) {
    if (isset($pages[$id])) {
        continue;
    }
    $r = resolve_page($id);
    $out .= '- `' . $entry['url'] . '` — ' . $r['page']['status']
          . ($r['page']['status'] === 'planned' ? ' (no content file yet)' : '') . "\n";
}

file_put_contents(PF_ROOT . '/docs/COPY-BRIEF.md', $out);
printf("docs/COPY-BRIEF.md written: %d passages across %d pages.\n", $totalSlots, count($pages));
